query orgStructure($id: ID!) {
  organization(id: $id) {
    # depend {
    #   id
    #   name
    # }
    departments {
      id
      name
      parent {
        id
        name
      }
    }
  }
}

query organizations {
  organizations {
    id
    name
    # depend {
    #   id
    #   name
    # }
  }
}

# 新建用户
mutation addUser($input: EmployeeCreateInput!) {
  createEmployee(input: $input) {
    id
    name
    jobNumber
    departments {
      id
      name
    }
  }
}

# 更新用户
mutation updateUser($id: ID!, $input: EmployeeUpdateInput!) {
  updateEmployee(id: $id, input: $input) {
    id
    name
    jobNumber
    departments {
      id
      name
    }
  }
}

#删除用户
mutation delUser($id: ID!) {
  removeEmployee(id: $id)
}

# 查询部门信息
query getDept {
  organizations {
    departments {
      id
      name
    }
  }
}

query employees($organization: ID!, $page: Int, $pageSize: Int = 10, $orderBy: OrderBy, $filter: EmployeeFilter) {
  employees(organization: $organization, page: $page, pageSize: $pageSize, orderBy: $orderBy, filter: $filter) {
    total: totalCount
    pageSize
    current: currentPage
    edges {
      node {
        id
        status
        name
        jobNumber
        birthday
        sex
        mobile
        tel
        user{
          username
        }
         email{
            id
            status
            email
          }
        departments(organization: $organization) {
          id
          name
          fullName
          path
          parents {
            id
            name
          }
        }
      }
    }
  }
}

# 根据id查询部门
query queryDepartmentInfo($id: ID!,$organization:ID!) {
  department(id: $id) {
    name
    id
    jobs {
      id
      name
    }
    positions {
      id
      name
    }
    parent {
      id
      name
    }
    employees {
      id
      status(organization:$organization){
        id
        name
      }
      jobNumber
      avatar
      name
      birthday
      sex
      mobile
      tel
      email{
            id
            email
          }
      positions {
        id
        name
      }
    }
  }
}

query getDepartment($id: ID!) {
  department(id: $id) {
    name
    id
    jobs {
      id
      name
    }
    positions {
      id
      name
    }
    parent {
      id
      name
    }
    organization {
      id
      name
    }
  }
}

# 查询全部部门
query queryDepartments($organization: ID!) {
  departments(organization: $organization) {
    id
    name
    parent {
      id
      name
    }
    positions {
      id
      name
    }
  }
}

# 查询单个用户信息
query employee($id: ID!, $organization: ID!) {
  organization(id: $organization){
    id
    name
  }
  employee(id: $id) {
    id
    status
    jobNumber
    avatar
    name
    birthday
    sex
    mobile
    tel
     email{
            id
            status
            email
          }
    positions(organization: $organization) {
      id
      name
      department {
        id
        name
      }
    }
    primaryPosition(organization: $organization) {
      id
      name
    }
    primaryDepartment (organization: $organization) {
      id
      name
      organization {
        id
        name
      }
    }
  }
}

# 批量更新员工职位
mutation batchUpdateEmployeePosition($employees: [ID]!, $position: ID!) {
  batchUpdateEmployeePosition(employees: $employees, position: $position)
}
