query getSchema {
  schema(id: "master") {
    id
    name
    ungrouped {
      id
      name
      type
      resourceId
      resourceType
    }
    endpoints {
      id
      code
      name
      type {
        id
        code
        name
      }
      model {
        id
        code
      }
    }
    groups {
      id
      name
      description
      items {
        id
        resourceId
        resourceType
      }
    }
  }
}
