

# 获取所有模块和使用状态
query getCases($applicationId: ID!){
  cases{
    id
    icon
    name
    install(applicationId: $applicationId)
    version{
      id
      name
      version
      description
      use(applicationId: $applicationId)
    }
  }
}


# 安装模块
mutation caseUseApplication(
  $caseId: String!,
  $version: String!,
  $applicationId: String! ) {
  caseUseApplication(caseId: $caseId,version: $version, applicationId: $applicationId ) {
    id
    name
  }
}

# 卸载模块
mutation removeCaseUseApplication(
  $caseId: String!,
  $version: String!,
  $applicationId: String! ) {
  removeCaseUseApplication(caseId: $caseId,version: $version, applicationId: $applicationId )
}
